# This RBAC file should be applied if custom-tekton-listener is deployed in a different namespace
# where the tekton pipelines live
# In this case custom-tekton-listener is deployed in custom-tekton-listener namespace and pipelines
# in tekton-pipelines

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: custom-tekton-listener
  namespace: custom-tekton-listener-pro
rules:
- apiGroups: [""]
  resources: 
    - "configmaps"
    - "secrets"
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: custom-tekton-listener
  namespace: custom-tekton-listener-pro
subjects:
- kind: ServiceAccount
  name: custom-tekton-listener
  namespace: custom-tekton-listener-pro
roleRef:
  kind: Role 
  name: custom-tekton-listener
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-pipelineruns
  namespace: tekton-pipelines-pro
subjects:
- kind: ServiceAccount
  name: custom-tekton-listener
  namespace: custom-tekton-listener-pro
roleRef:
  kind: ClusterRole 
  name: tekton-pipelineruns-create
  apiGroup: rbac.authorization.k8s.io
